# Generated by Django 3.2.25 on 2024-06-22 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Customer Enquiries'},
        ),
    ]
